# Generated by Django 5.2 on 2025-04-26 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CartItem', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Cart', to='orders.cartitem')),
            ],
        ),
    ]
