# Generated by Django 5.2 on 2025-05-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_cartitem_cart_remove_cartitem_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('on_deliver', 'on_deliver'), ('canceled', 'canceled'), ('completed', 'completed')], default='waiting', max_length=100),
        ),
    ]
